hmrc/agent-permissions-frontend

- app/connectors/AgentUserClientDetailsConnector.scala
- app/controllers/GroupController.scala
- app/controllers/SessionBehaviour.scala
- app/controllers/package.scala
- app/models/Client.scala
- app/models/Group.scala
- app/services/ClientListService.scala
- app/views/groups/client_group_list.scala.html
- conf/app.routes
- project/AppDependencies.scala
- test/connectors/AgentUserClientDetailsConnectorSpec.scala
- test/controllers/GroupControllerSpec.scala
- test/helpers/AgentUserClientDetailsConnectorMocks.scala
- test/services/SessionCacheServiceSpec.scala
- replace Enrolment model with the library Client model for the client list. 
- fix routing issue when coming from ASA to create a group.
- remove obfuscation of client id's for now.
> fix routing issue when coming from ASA to create a group

- app/views/groups/client_group_list.scala.html
- app/views/groups/team_members_list.scala.html
with MOJ sortable table & multi-select
> APB-6057 [CS] update team members list

- app/utils/ViewUtils.scala
- app/views/components/input_select.scala.html
- app/views/components/submit_button_group.scala.html
- app/views/groups/client_group_list.scala.html
- app/views/groups/team_members_list.scala.html
- conf/messages
- conf/messages.cy
client list and team member list (both non-functional)
> APB-5943 [CS] adds FE components for filters

- app/connectors/AgentPermissionsConnector.scala
- app/controllers/GroupController.scala
- app/controllers/ManageGroupController.scala
- app/controllers/package.scala
- app/forms/GroupNameForm.scala
- app/views/components/a.scala.html
- app/views/groups/manage/dashboard.scala.html
- app/views/groups/manage/group_not_found.scala.html
- app/views/groups/manage/rename_group.scala.html
- app/views/groups/manage/rename_group_complete.scala.html
- conf/app.routes
- conf/messages
- project/CodeCoverageSettings.scala
- test/connectors/AgentPermissionsConnectorSpec.scala
- test/controllers/GroupControllerSpec.scala
- test/controllers/ManageGroupControllerSpec.scala
- test/forms/ConfirmGroupNameFormSpec.scala
- test/forms/GroupNameFormSpec.scala
- test/helpers/AgentPermissionsConnectorMocks.scala
- test/helpers/Css.scala
- test/helpers/HttpClientMocks.scala
Finished bar the refactoring of the Back End
> APB-6115 Rename Access Group

- app/controllers/GroupController.scala
- app/controllers/package.scala
- app/forms/AddTeamMembersToGroupForm.scala
- app/models/AddTeamMembersToGroup.scala
- app/models/ButtonSelect.scala
- app/services/GroupService.scala
- app/views/components/submit_button_group.scala.html
- app/views/groups/team_members_list.scala.html
- build.sbt
- conf/messages
- project/CodeCoverageSettings.scala
- test/controllers/GroupControllerSpec.scala
- test/forms/AddClientsToGroupFormSpec.scala
- test/forms/AddTeamMembersToGroupFormSpec.scala
- test/models/ButtonSelectSpec.scala
- test/services/GroupServiceSpec.scala
Also fixes case sensitivity & clear button in client filters.
I'm not sure if it meets coverage yet because intelliJ keeps bugging out :(
and need to merge main again it seems.
> APB-5941 add team filters

- app/views/groups/create.scala.html
- test/controllers/GroupControllerSpec.scala
> Apb 6166 update back link

- app/views/groups/client_group_list.scala.html
- app/views/groups/team_members_list.scala.html
and updates span to use messages key
> [CS] fix errorHref for client list

- app/controllers/GroupController.scala
- app/controllers/ManageGroupController.scala
- app/controllers/SessionBehaviour.scala
- app/forms/AddTeamMembersToGroupForm.scala
- app/views/groups/review_clients_to_add.scala.html
refactor Group controller a bit to remove common copy pasted code
> APB-6121 tidy up GroupController

- app/controllers/ManageGroupController.scala
- app/views/groups/manage/dashboard.scala.html
- app/views/groups/manage/view_team_members.scala.html
- app/views/groups/team_members_list.scala.html
- conf/app.routes
- conf/messages
- project/CodeCoverageSettings.scala
- test/controllers/ManageGroupControllerSpec.scala
Routes I added here bc the diff in git highlights everything :P 
```
GET     /manage-group-team-members/:groupId     controllers.ManageGroupController.showViewGroupTeamMembers(groupId: String)
GET     /update-group-team-members/:groupId     controllers.ManageGroupController.showManageGroupTeamMembers(groupId: String)
```
> APB-6123 [CS] add view team members page

- app/controllers/ManageGroupController.scala
not sure how these disappeared but a quick fix
> APB-6123 [CS] missing imports

- app/controllers/ManageGroupController.scala
- app/controllers/package.scala
- app/forms/SelectGroupsForm.scala
- app/views/groups/manage/clients_added_to_groups_complete.scala.html
- app/views/groups/unassigned_clients/select_groups_for_clients.scala.html
- build.sbt
- conf/app.routes
- conf/messages
- project/AppDependencies.scala
- test/controllers/ManageGroupControllerSpec.scala
- test/forms/SelectGroupsFormSpec.scala
Still have to refactor quite a bit. but it's working.
> Apb 6129 adding unassigned clients to groups

- app/views/group_member_details/client_details.scala.html
>  APB-6188 [CS] update headers on client details

- app/forms/FilterByGroupNameForm.scala
- app/views/groups/manage/dashboard.scala.html
- app/views/partials/selectable_clients_table_form.scala.html
- test/controllers/ManageGroupControllerSpec.scala
"search" was used twice, one on each tab
> Apb 6242 a11y [CS] fix blank labels and double label

- app/connectors/AgentPermissionsConnector.scala
- app/controllers/ManageTeamMemberController.scala
- app/services/ManageTeamMemberService.scala
- app/utils/ViewUtils.scala
- app/views/group_member_details/client_details.scala.html
- app/views/group_member_details/team_member_details.scala.html
- app/views/groups/manage/existing_team_members.scala.html
- app/views/groups/review_team_members_to_add.scala.html
- app/views/groups/team_members_list.scala.html
- app/views/partials/team_members_details_table_filter_form.scala.html
- conf/messages
- project/CodeCoverageSettings.scala
- test/connectors/AgentPermissionsConnectorSpec.scala
- test/controllers/GroupControllerSpec.scala
- test/controllers/ManageGroupTeamMembersControllerSpec.scala
- test/controllers/ManageTeamMemberControllerSpec.scala
- test/helpers/AgentPermissionsConnectorMocks.scala
also updates display of team member role via `displayTeamMemberRole` in `ViewUtils`
I'm working on an update for the link to each details page but I want this ^ merged
> APB-6250 [CS] add team_member_details page

- app/connectors/AgentPermissionsConnector.scala
- app/connectors/AgentUserClientDetailsConnector.scala
- app/controllers/ManageGroupController.scala
- app/controllers/package.scala
- app/services/GroupService.scala
- app/views/groups/manage/dashboard.scala.html
- app/views/groups/manage/existing_clients.scala.html
- app/views/groups/manage/existing_team_members.scala.html
- app/views/partials/clients_details_table_filter_form.scala.html
- app/views/partials/team_members_details_table_filter_form.scala.html
- conf/messages
adds content for search & filter when no results
adds counter on more list pages
remembers search term for unassigned tab
> [CS] add content and update unassigned clients tab

- app/controllers/ManageGroupClientsController.scala
- app/views/groups/manage/existing_clients.scala.html
- app/views/groups/manage/update_client_group_list.scala.html
- app/views/partials/selectable_clients_table_form.scala.html
- conf/app.routes
- conf/messages
- conf/messages.cy
- test/controllers/GroupControllerSpec.scala
- test/controllers/ManageGroupClientsControllerSpec.scala
- test/controllers/ManageGroupControllerSpec.scala
- url update
- content updates
- show 'not found' content when searching for client and no results (instead of empty table)
> Abp-6229 [CS] update manage client pages

- app/controllers/ManageGroupClientsController.scala
- app/views/groups/manage/review_update_clients.scala.html
- app/views/groups/review_clients_to_add.scala.html
- conf/app.routes
- conf/messages
- test/controllers/GroupControllerSpec.scala
- test/controllers/ManageGroupClientsControllerSpec.scala
- update content for select clients page
- fixes functionality of radio for manage group clients review
> APB-6218 & APB-6230 [CS] update radios for clients

- app/controllers/CreateGroupController.scala
- app/controllers/ManageGroupClientsController.scala
- app/controllers/ManageGroupController.scala
- app/views/groups/access_group_name_exists.scala.html
- app/views/groups/check_your_answers.scala.html
- app/views/groups/client_group_list.scala.html
- app/views/groups/confirm_group_name.scala.html
- app/views/groups/create.scala.html
- app/views/groups/manage/dashboard.scala.html
- app/views/groups/manage/review_update_clients.scala.html
- app/views/groups/manage/update_client_group_list.scala.html
- app/views/groups/review_clients_to_add.scala.html
- app/views/groups/review_team_members_to_add.scala.html
- app/views/groups/team_members_list.scala.html
- app/views/partials/selectable_clients_table_form.scala.html
- app/views/you_have_opted_in.scala.html
- conf/app.routes
- test/controllers/CreateGroupControllerSpec.scala
- test/controllers/ManageGroupControllerSpec.scala
- test/controllers/OptInControllerSpec.scala
- FYI we've missed updating the unassigned clients review to handle radios, I will raise a separate PR since renaming the controller took more changes than I thought!
> Refac [CS] rename GroupController to CreateGroupController

- app/connectors/AgentPermissionsConnector.scala
- app/controllers/OptInController.scala
- app/services/OptInService.scala
- test/connectors/AgentPermissionsConnectorSpec.scala
- test/helpers/AgentPermissionsConnectorMocks.scala
Linked PRs:
https://github.com/hmrc/agent-user-client-details/pull/42
https://github.com/hmrc/agent-permissions/pull/48
> APB-6204 Explicit language setting for email

- app/views/components/models/SummaryListData.scala
- app/views/components/summary_list.scala.html
- app/views/groups/check_your_answers.scala.html
- app/views/groups/manage/dashboard.scala.html
- test/controllers/CreateGroupControllerSpec.scala
- test/controllers/ManageGroupControllerSpec.scala
+rename/delete links on dashboard
> apb-6403 [CS] add visuallyHiddenText to summary list

- app/controllers/ManageGroupController.scala
- app/controllers/UnassignedClientController.scala
- app/views/groups/manage/dashboard.scala.html
- app/views/groups/unassigned_clients/select_groups_for_clients.scala.html
- conf/app.routes
- test/controllers/ManageGroupControllerSpec.scala
- test/controllers/UnassignedClientControllerSpec.scala
splitting controller - no functional change
> APB-6404-part1 [CS] refactor unassigned clients

- app/controllers/CreateGroupController.scala
- app/views/components/radioButtons.scala.html
- app/views/groups/confirm_group_name.scala.html
- app/views/groups/manage/confirm_delete_group.scala.html
- app/views/groups/manage/review_update_clients.scala.html
- app/views/groups/manage/review_update_team_members.scala.html
- app/views/groups/review_clients_to_add.scala.html
- app/views/groups/review_team_members_to_add.scala.html
- app/views/want_to_opt_in.scala.html
- app/views/want_to_opt_out.scala.html
- conf/messages
- test/controllers/CreateGroupControllerSpec.scala
- test/controllers/ManageGroupClientsControllerSpec.scala
- test/controllers/ManageGroupControllerSpec.scala
- test/controllers/ManageGroupTeamMembersControllerSpec.scala
- test/controllers/OptInControllerSpec.scala
- test/controllers/OptOutControllerSpec.scala
- test/controllers/UnassignedClientControllerSpec.scala
so id of first input matches error href on Error summary
> apb-6429 [CS] update radioButtons

- app/views/components/input_select.scala.html
- app/views/groups/client_group_list.scala.html
- app/views/groups/manage/dashboard.scala.html
- app/views/groups/manage/existing_clients.scala.html
- app/views/groups/manage/update_client_group_list.scala.html
- app/views/groups/unassigned_clients/unassigned_clients_list.scala.html
- app/views/partials/clients_details_table_filter_form.scala.html
- app/views/partials/selectable_clients_table_form.scala.html
- conf/messages
to have text for empty option
also APB-6457 content update on select clients page to latest design
> apb-6458 [CS] update select component

- app/forms/ClientReferenceForm.scala
- app/forms/ConfirmCreateGroupForm.scala
- app/forms/GroupNameForm.scala
- conf/messages
- conf/messages.cy
- test/controllers/CreateGroupControllerSpec.scala
- test/controllers/ManageGroupControllerSpec.scala
- test/forms/ClientReferenceFormSpec.scala
- test/forms/ConfirmGroupNameFormSpec.scala
- test/forms/FilterByGroupNameFormSpec.scala
- test/forms/GroupNameFormSpec.scala
update client ref regex to not allow spaces
> APB-6440 [CS] update group name forms to use regex

- conf/messages
- conf/messages.cy
should be fully translated now
> APB-6460 [CS] add extra welsh

- app/config/AppConfig.scala
- app/controllers/AssistantViewOnlyController.scala
- app/controllers/AuthAction.scala
- app/controllers/GroupAction.scala
- app/views/assistant_read_only/existing_group_client_list.scala.html
- app/views/assistant_read_only/unassigned_client_list.scala.html
- app/views/groups/unassigned_clients/unassigned_clients_list.scala.html
- app/views/partials/clients_table_filter_form.scala.html
- conf/app.routes
- conf/application.conf
- conf/messages
- conf/messages.cy
- test/controllers/AssistantViewOnlyControllerSpec.scala
- test/helpers/BaseSpec.scala
- draft (still need to get coverage up)
> APB-6274 [CS] add standard user views

- app/views/groups/team_members_list.scala.html
- app/views/partials/selectable_clients_table_form.scala.html
- app/views/partials/selectable_team_members_table_form.scala.html
- conf/messages
- conf/messages.cy
- test/controllers/CreateGroupControllerSpec.scala
> APB-6482-part1 [CS] add skip link to create journey

- app/views/assistant_read_only/unassigned_client_list.scala.html
- test/controllers/AssistantViewOnlyControllerSpec.scala
for unassigned client list assistant users
> APB-6274 [CS] fix search/filter form

- app/controllers/CreateGroupController.scala
- app/controllers/ManageGroupClientsController.scala
- app/controllers/ManageGroupTeamMembersController.scala
- app/controllers/package.scala
- app/services/ClientService.scala
- app/services/TeamMemberService.scala
- test/services/TeamMemberServiceSpec.scala
- also ensures user input for search/filter is remembered and played back (clients & team members)
> Apb6493 [CS] bugfix allows user to search multiple times

- app/utils/ViewUtils.scala
- app/views/groups/client_group_list.scala.html
- app/views/groups/manage/update_client_group_list.scala.html
- app/views/groups/team_members_list.scala.html
- app/views/groups/unassigned_clients/unassigned_clients_list.scala.html
- app/views/partials/clients_details_table_filter_form.scala.html
- app/views/partials/selectable_clients_table_form.scala.html
- app/views/partials/selectable_team_members_table_form.scala.html
- app/views/partials/team_members_details_table_filter_form.scala.html
- conf/messages
- conf/messages.cy
- test/controllers/CreateGroupControllerSpec.scala
- test/controllers/ManageGroupClientsControllerSpec.scala
- test/controllers/ManageGroupTeamMembersControllerSpec.scala
- test/controllers/UnassignedClientControllerSpec.scala
Please review and squash & merge if merging
> APB-6487b [CS] add h2 and title prefix when search/filters applied

- app/views/groups/unassigned_clients/unassigned_clients_list.scala.html
for unassigned clients list when no clients found
> APB-6488 [CS] add missing role "search"

- app/controllers/CreateGroupSelectClientsController.scala
- app/controllers/CreateGroupSelectTeamMembersController.scala
- app/controllers/package.scala
- app/views/groups/create/review_clients_paginated.scala.html
- app/views/groups/create/review_members_paginated.scala.html
- conf/app.routes
- project/CodeCoverageSettings.scala
- test/controllers/CreateGroupSelectTeamMembersControllerSpec.scala
> APB-6688 [CS] paginate review selected clients

- app/connectors/AgentPermissionsConnector.scala
- app/controllers/ManageGroupController.scala
- app/views/components/h2.scala.html
- app/views/groups/manage/dashboard.scala.html
- project/AppDependencies.scala
- test/connectors/AgentPermissionsConnectorSpec.scala
- test/controllers/AddClientToGroupsControllerSpec.scala
- test/controllers/AddTeamMemberToGroupsControllerSpec.scala
- test/controllers/AssistantViewOnlyControllerSpec.scala
- test/controllers/ManageClientControllerSpec.scala
- test/controllers/ManageGroupControllerSpec.scala
- test/controllers/ManageTeamMemberControllerSpec.scala
- test/controllers/UnassignedClientControllerSpec.scala
- test/services/GroupServiceSpec.scala
bump mtd-identifiers to 0.51.0 - update existing 'Manage group' view to handle optional client count
> APB-6728a [CS] use new Access Group Summary

- app/connectors/AgentPermissionsConnector.scala
- app/connectors/AgentUserClientDetailsConnector.scala
- app/controllers/CreateGroupSelectGroupTypeController.scala
- app/services/ClientService.scala
- app/utils/ViewUtils.scala
- test/connectors/AgentPermissionsConnectorSpec.scala
- test/connectors/AgentUserClientDetailsConnectorSpec.scala
- test/controllers/CreateGroupSelectGroupTypeControllerSpec.scala
- test/helpers/AgentPermissionsConnectorMocks.scala
- test/helpers/AgentUserClientDetailsConnectorMocks.scala
- test/helpers/ClientServiceMocks.scala
- test/services/ClientServiceSpec.scala
Update endpoints for client count by tax service
https://github.com/hmrc/agent-user-client-details/pull/74
https://github.com/hmrc/agent-permissions/pull/72
> [CS] update client count to use new endpoint

- app/controllers/ManageGroupController.scala
- app/controllers/UnassignedClientController.scala
- app/services/ClientService.scala
- app/services/GroupService.scala
- app/services/TaxGroupService.scala
- app/views/groups/manage/clients_update_complete.scala.html
- app/views/groups/manage/confirm_delete_group.scala.html
- app/views/groups/manage/delete_group_complete.scala.html
- app/views/groups/manage/existing_clients.scala.html
- app/views/groups/manage/existing_team_members.scala.html
- app/views/groups/manage/group_not_found.scala.html
- app/views/groups/manage/manage_existing_groups.scala.html
- app/views/groups/manage/rename_group.scala.html
- app/views/groups/manage/rename_group_complete.scala.html
- app/views/groups/manage/team_members_update_complete.scala.html
- conf/app.routes
- conf/messages
- conf/messages.cy
- test/controllers/ManageGroupClientsControllerSpec.scala
- test/controllers/ManageGroupControllerSpec.scala
- test/controllers/ManageGroupTeamMembersControllerSpec.scala
- test/helpers/GroupServiceMocks.scala
- test/helpers/TaxGroupServiceMocks.scala
- test/services/ClientServiceSpec.scala
- test/services/TaxGroupServiceSpec.scala
- adds tags depending on group type
- push group search logic into service
> Apb 6728 [CS] paginate manage group page

- app/controllers/CreateGroupSelectClientsController.scala
- app/controllers/CreateGroupSelectGroupTypeController.scala
- app/controllers/CreateGroupSelectNameController.scala
- app/controllers/CreateGroupSelectTeamMembersController.scala
- app/controllers/actions/GroupAction.scala
- app/services/GroupService.scala
- app/views/groups/create/members/select_paginated_team_members.scala.html
- app/views/groups/create/name/choose_name.scala.html
- app/views/groups/create/name/confirm_name.scala.html
- conf/app.routes
- test/controllers/CreateGroupSelectClientsControllerSpec.scala
- test/controllers/CreateGroupSelectGroupTypeControllerSpec.scala
- test/controllers/CreateGroupSelectNameControllerSpec.scala
- test/controllers/CreateGroupSelectTeamMembersControllerSpec.scala
- test/controllers/actions/AuthActionSpec.scala
- test/helpers/GroupServiceMocks.scala
- test/services/GroupServiceSpec.scala
update GroupAction to ensure GroupType
> APB-6791 [CS] add rename tax service group

- app/connectors/AgentPermissionsConnector.scala
- app/controllers/ManageGroupClientsController.scala
- app/controllers/ManageGroupController.scala
- app/controllers/actions/GroupAction.scala
- app/services/GroupService.scala
- app/services/TaxGroupService.scala
- app/views/groups/manage/confirm_delete_group.scala.html
- app/views/groups/manage/rename_group.scala.html
- test/connectors/AgentPermissionsConnectorSpec.scala
- test/controllers/ManageGroupControllerSpec.scala
- test/helpers/TaxGroupServiceMocks.scala
- test/services/TaxGroupServiceSpec.scala
+ replace groups with summaries
> APB-6853a [CS] fix get tax group type

- app/assets/stylesheets/application.scss
- app/forms/GroupNameForm.scala
- app/views/groups/group_created.scala.html
- conf/messages
- test/controllers/CreateGroupControllerSpec.scala
- test/controllers/CreateGroupSelectNameControllerSpec.scala
- test/forms/GroupNameFormSpec.scala
Changes made to replace Char length 32 to 50 (FE)
> APB 6855 RW

- app/assets/stylesheets/application.scss
- app/controllers/CreateGroupSelectGroupTypeController.scala
- app/views/groups/create/groupType/exceed_group_selection.scala.html
- conf/messages
- test/controllers/CreateGroupSelectGroupTypeControllerSpec.scala
- test/helpers/ClientServiceMocks.scala
User creates groups using all of the possible tax options then is redirected
> APB-6854 [RW] add "created all tax groups" page

- app/controllers/AddClientToGroupsController.scala
- app/controllers/AddTeamMemberToGroupsController.scala
- app/views/group_member_details/add_groups_to_client/select_groups.scala.html
- app/views/group_member_details/add_groups_to_team_member/select_groups.scala.html
- app/views/groups/create/groupType/review_group_type.scala.html
- app/views/groups/manage/clients/existing_clients.scala.html
- conf/messages
- test/controllers/AddClientToGroupsControllerSpec.scala
- test/controllers/AddTeamMemberToGroupsControllerSpec.scala
hides tax service groups for add client to groups
> APB-6923 [CS] add client to custom groups only

- app/controllers/ManageClientController.scala
- app/controllers/ManageGroupClientsController.scala
- app/controllers/ManageGroupController.scala
- app/controllers/ManageGroupTeamMembersController.scala
- app/controllers/ManageTaxGroupClientsController.scala
- app/controllers/ManageTeamMemberController.scala
- app/controllers/package.scala
- app/services/TeamMemberService.scala
- app/views/group_member_details/manage_team_members.scala.html
- app/views/group_member_details/team_member_details.scala.html
- app/views/groups/manage/members/existing_group_team_members.scala.html
- app/views/groups/manage/members/review_update_team_members.scala.html
- app/views/groups/manage/members/update_paginated_team_members.scala.html
- app/views/partials/paginated_selectable_team_members_table_form.scala.html
- app/views/partials/team_members_details_table_filter_form.scala.html
- conf/app.routes
- project/AppDependencies.scala
- test/controllers/ManageTeamMemberControllerSpec.scala
- test/helpers/Css.scala
* APB-6927 refactor manage team members to not use GET request ---------
Co-authored-by: Max Ashton <max.ashton@digital.hmrc.gov.uk>
> APB-6838 [MA] refactor manage team members to not use GET request (#270)

- conf/application.conf
removes "https://code.jquery.com/jquery-3.6.0.min.js" from allowed origins
> APB-6928 [CS] remove CORS config

- app/controllers/CreateGroupSelectClientsController.scala
- app/views/groups/create/clients/review_clients_paginated.scala.html
- app/views/groups/manage/clients/review_update_clients.scala.html
- conf/messages
- conf/messages.cy
- test/controllers/CreateGroupSelectClientsControllerSpec.scala
- test/controllers/ManageGroupClientsControllerSpec.scala
- test/controllers/UnassignedClientControllerSpec.scala
> APB-6938b [CS] add empty error to review clients (create journey)

- app/controllers/CreateGroupSelectClientsController.scala
- app/controllers/CreateGroupSelectTeamMembersController.scala
- app/views/groups/create/members/review_members_paginated.scala.html
- conf/messages
- conf/messages.cy
- test/controllers/CreateGroupSelectTeamMembersControllerSpec.scala
- test/controllers/ManageGroupTeamMembersControllerSpec.scala
- test/controllers/ManageTaxGroupTeamMembersControllerSpec.scala
> APB-6940 [CS] add empty error to review team members (create journey)

- app/controllers/CreateGroupSelectClientsController.scala
- app/views/groups/create/clients/review_clients_paginated.scala.html
- conf/app.routes
- test/controllers/CreateGroupSelectClientsControllerSpec.scala
APB-6938_RW - Remove welsh toggle
> APB-6938_RW - Remove error on welsh toggle

- app/controllers/CreateGroupSelectTeamMembersController.scala
- app/views/groups/create/members/review_members_paginated.scala.html
- conf/app.routes
- test/controllers/CreateGroupSelectTeamMembersControllerSpec.scala
> APB-6951 [RW] fix TeamMemberRemove

- app/controllers/AssistantViewOnlyController.scala
- app/views/assistant_read_only/existing_group_client_list.scala.html
> APB-7090 [CS] fix TG form action

- app/config/AppConfig.scala
- app/utils/ViewUtils.scala
- conf/application.conf
- conf/messages
- conf/messages.cy
- project/AppDependencies.scala
- test/controllers/CreateGroupSelectGroupTypeControllerSpec.scala
- test/helpers/ClientServiceMocks.scala
Prod config PR: https://github.com/hmrc/app-config-production/pull/19165
Feature flag only used for the available filters since we define that here, the rest of the display support ie. of clients will be covered by the AUCD flag
> APB-7299 [CS] add cbc to filters (behind FF)

- app/views/partials/existing_group_paginated_selectable_team_members_table_form.scala.html
- app/views/partials/paginated_selectable_team_members_table_form.scala.html
APB-7381_RW change skip-to-team member to display the correct message
> APB-7381_RW change skip-to-team member to display the correct message

- app/controllers/CreateGroupSelectClientsController.scala
- app/controllers/CreateGroupSelectGroupTypeController.scala
- app/controllers/CreateGroupSelectNameController.scala
- app/controllers/CreateGroupSelectTeamMembersController.scala
- app/controllers/ManageGroupClientsController.scala
- app/controllers/UnassignedClientController.scala
- app/controllers/package.scala
- app/forms/TaxServiceGroupTypeForm.scala
- conf/project/build.properties
- project/AppDependencies.scala
- project/plugins.sbt
- test/controllers/CreateGroupSelectClientsControllerSpec.scala
- test/controllers/CreateGroupSelectGroupTypeControllerSpec.scala
- test/controllers/CreateGroupSelectNameControllerSpec.scala
- test/controllers/CreateGroupSelectTeamMembersControllerSpec.scala
- test/controllers/ManageGroupClientsControllerSpec.scala
- test/controllers/UnassignedClientControllerSpec.scala
- fills data from the session into forms
- add additional confirm DataKeys to keep track of some yes/no responses.
> Apb 7379 [GW] fix data not maintained

- app/controllers/CreateGroupSelectClientsController.scala
- app/views/groups/create/clients/select_paginated_clients.scala.html
- app/views/groups/manage/clients/existing_clients.scala.html
- app/views/groups/manage/clients/existing_tax_group_clients.scala.html
- app/views/groups/manage/group_not_found.scala.html
- app/views/groups/manage/members/existing_group_team_members.scala.html
- conf/messages
- conf/messages.cy
- project/plugins.sbt
- test/controllers/CreateGroupSelectClientsControllerSpec.scala
- test/controllers/ManageGroupClientsControllerSpec.scala
- test/controllers/ManageGroupTeamMembersControllerSpec.scala
- test/controllers/ManageTaxGroupClientsControllerSpec.scala
- remove "back to search" hardcoding to prevent loop
- add "Back to manage groups" for team members / tax group clients to avoid issues after add/remove transaction (getting stuck in loop)
> APB-7380[CS] back link fixes

- app/assets/stylesheets/application.scss
To resolve A11y issue with table missing responsive layout (P1)
> APB-7391 [iw] add break-word wrapping to tables

- app/controllers/ManageGroupClientsController.scala
- test/controllers/ManageGroupClientsControllerSpec.scala
checks if client to remove from selected client still selected
> APB-7380[CS] confirm remove from selected clients

- app/models/Selectable.scala
- test/models/SelectableSpec.scala
(update order of enrolmentKey, cbcId is meant to be first not UTR)
> APB-7473 [CS] show cbcId not UTR for uk cbc

- app/config/AppConfig.scala
- app/utils/ViewUtils.scala
- conf/application.conf
- conf/messages
- conf/messages.cy
- project/AppDependencies.scala
- test/controllers/CreateGroupSelectGroupTypeControllerSpec.scala
- test/helpers/ClientServiceMocks.scala
- test/helpers/TaxGroupServiceMocks.scala
Pillar2 access group drop down filter/test. This is needed for Pillar 2 to be display on the FE
> APB-7453_RW Pillar2 access group filter/test for FE
